### ISSUE TITLE
Good toy

### ISSUE THREAD

**Issue by Genxgen** [radioelf/C245-JBC-control#1]
Good toy , if the function 'current limit'  available will be better, that can  avoid JBC heater be damaged by over current.

**Comment by JHS1211** [comment]
您好，您的这个JBC控制器很好，我制作了一个，但是，显示屏不正常，现在HX8352A的显示屏很少，而且与您的可能不是一样的，我用的自己制作的PCB，用的是44P的HX8352A  262K的显示屏，但是显示的意思不正常，缺少高8位的颜色，用的是2个74C245D,我用的这个屏是不是不对？您可否把程序改成262K的使用的程序？非常感谢。

**Comment by JHS1211** [comment]
![IMG_2797](https://user-images.githubusercontent.com/67097777/85006716-0fb13c00-b18d-11ea-8d1e-5c12348e9edd.JPG)
