### ISSUE TITLE
 C245-JBC-控制

### ISSUE THREAD

**Issue by JHS1211** [radioelf/C245-JBC-control#2]

**Comment by JHS1211** [comment]
> Hello, you JBC controller is very good, I made a, however, showed abnormal, HX8352A shows very little now, and you may not be the same, I use a pcset, using the 44 p HX352A 262 k, but the color is not normal, not high 8-bit color, there should be no red, I use low 8 drive, because of high eight white, 4 c, this is my screen? Program can be changed to 262 k application? Thank you very much.

> ![image](https://user-images.githubusercontent.com/67097777/85009731-7f292a80-b191-11ea-8915-35e03113e877.png)
> Can you change the program to support some ILI9327 LCD screen now? (pictured)
> ![image](https://user-images.githubusercontent.com/67097777/85010418-8a308a80-b192-11ea-8a42-32124eb3f4bf.png)
> This is too good, thanks again.

**Comment by radioelf** [comment]
Hi. I don't have any ILI9327 screen to test, you can try some examples from the library?, to validate the screen..

**Comment by JHS1211** [comment]
Hello, I didn't find the HX8352A you welding units use the LCD module, only found 16 HX8352A LCD module, I use this screen to change to use two 74 hc245d PCB, but only sent to the first picture shows the color, (pictured), I don't know what reason be? This screen is 262 k, your screen is 65 k? Display is not normal and this matter? I don't really understand this, thank you very much!

![IMG_2797](https://user-images.githubusercontent.com/67097777/85036646-f4f3bd00-b1b6-11ea-8800-f0ea155e4029.JPG)

**Comment by JHS1211** [comment]
这是我自己画的PCB，不知有什么问题？希望您能给与指教。感谢！
![lcd](https://user-images.githubusercontent.com/67097777/85038286-fe7e2480-b1b8-11ea-840c-43859094950d.JPG)
[TM032LDH05.pdf](https://github.com/radioelf/C245-JBC-control/files/4799429/TM032LDH05.pdf)

**Comment by radioelf** [comment]
HI, try to validate your lcd with some simple example from the library, I don't have  ILI9327, to check the problem.

https://github.com/prenticedavid/MCUFRIEND_kbv/tree/master/examples

**Comment by JHS1211** [comment]
[TM032LDH05.pdf](https://github.com/radioelf/C245-JBC-control/files/4799479/TM032LDH05.pdf)

**Comment by JHS1211** [comment]
谢谢您的指教，这个屏可以用在您的焊台上吗？

**Comment by radioelf** [comment]
Now I have no screen to test,,,

**Comment by JHS1211** [comment]
You this soldering station using HX8352A LCD module where I can buy? Thank you very much!

**Comment by radioelf** [comment]
Yes, But you can modify/settings the library to use another LCD.

https://github.com/prenticedavid/MCUFRIEND_kbv/blob/master/extras/mcufriend_how_to.txt

**Comment by JHS1211** [comment]
Thank you, I was too stupid, don. Don't change program, have LCD screen assembly line still available.
If you can buy with LCD modules to assemble.

**Comment by JHS1211** [comment]
Hello, I ask, do you have 3.2 240 x400 HA8352A LCD module specifications and materials? Can you share? Thank you very much!
