### ISSUE TITLE
C245-JBC

### ISSUE THREAD

**Issue by JHS1211** [radioelf/C245-JBC-control#3]
Hello, I ask, do you have 3.2 240 x400 HA8352A LCD module specifications and materials? Can you share? Thank you very much!

**Comment by radioelf** [comment]
Hi. you can look https://www.youtube.com/watch?v=2_4dZHR1aU0 and https://drive.google.com/drive/folders/1C7fec55cgBTltYG_zs_t0RN0wg24lncN , I don't have HA8352A LCD...

**Comment by JHS1211** [comment]
Hello, I made your soldering station, but show the temperature there is a problem, in the program, the highest temperature setting dormancy temperature and set temperature show 65535, cannot adjust, what's the problem? Look forward to your comments, thank you.


![IMG_3028](https://user-images.githubusercontent.com/67097777/94022865-1f719980-fde8-11ea-9709-f62529b2babd.JPG)

**Comment by radioelf** [comment]
Hi. temperature maximum, standby and run are of type uint16_t (0-65535), in lines 68, 69 and 71 of the code, are the initial values (default):
uint16_t Temp_Max[3] = {450, 450, 450};                           // temperatura máxima 450 °C M1, M2, M3
uint16_t Temp_Standby[3] = {180, 200, 225};                    // temperatura en modo standby M1, M2, M3
uint16_t Ini_Temp[3] = {340, 350 , 375};                            // temperatura inicial de trabajo M1, M2, M3
minimum temperature is correct (type uint8_t), this makes me think of a mistake when reading the EEPROM, I see the problem ... it is found by not compiling the code, with line 174 NOT commented "for (uint8_t x = 0; x < 16; x++) {EepromTx(x);}" so that the initial values are written in the EEPROM, a solution is to program the values in your EEPROM with the application that you use to program the arduino Mega, you can program 0x00 (positions of  0 to 36) and then set your values (I think it will work?)

**Comment by JHS1211** [comment]
Yes MEGA2560


发自我的iPhone

------------------ Original ------------------

**Comment by JHS1211** [comment]
Hello, thank you for your reply, I'm very sorry, I'm not to modify the code, you can block the EEPROM to modify good, send me a, can? Various temperature setting code value is good for you, thank you very much!

**Comment by radioelf** [comment]
Hi.
I don't have much time for testing, I have made some small changes, can you try?
https://www.dropbox.com/sh/hsiqosuhe77o3pt/AADwNDIiTPp5T8JGyA_KDvUna?dl=0

**Comment by JHS1211** [comment]
hello
I did a test, it is white, my screen drive is ILI9327, might be driving it?
I and brush into my original ILI9327 firmware, according to normal, but the two lower temperature on the arrow, press which is cool, up arrow does not heat up and cool instead.

**Comment by radioelf** [comment]
Hello.
I don't have a ILI9327 screen (for testing), you can try to program with its previous version, if the EEPROM was programmed correctly (with the latest version) it could work....

**Comment by JHS1211** [comment]
hello
I won't be programming, you block the EEPROM compile best good, send me a copy.
ILI9327 yourself, can I?

**Comment by JHS1211** [comment]
Why can only cool when welding machine heating? Warming up arrow touch, but cool.
Is at work can not raise the temperature?

**Comment by radioelf** [comment]
Block the EEPROM, means much code modification; you may NOT increase the temperature for safety reasons, as the values are out of range....

**Comment by JHS1211** [comment]
Both up and down arrow is to adjust temperature? Only can regulate the temperature of a standby?
![3,2](https://user-images.githubusercontent.com/67097777/94139340-10e4ba00-fe9c-11ea-98c2-fd661206ff26.png)

**Comment by JHS1211** [comment]
Why can't work only the cooling up? Is this normal?
[IMG_3034.zip](https://github.com/radioelf/C245-JBC-control/files/5275645/IMG_3034.zip)

**Comment by radioelf** [comment]
You can see a video of the operation https://www.youtube.com/watch?v=qMxd-N4Ooyk ; in the picture is NOT in the mode  standby; in the video it seems that the calibration of the keyboard-screen is not working properly, it is necessary to compile the code for your screen

**Comment by JHS1211** [comment]
Yes, in the video, don't have the operation, you really need to screen the compiled code, the soldering station how beautiful ah, you should improve his, otherwise it's too bad.
Again, the output of the MOS tube is too hot, hot, shouldn't be so hot, what's the solution?

**Comment by radioelf** [comment]
My station is working fine, and the code is free on github for anyone who wants to use/improve it, i don't have time to make changes now...

**Comment by JHS1211** [comment]
Your workstation using AC16V AC24V can use?

**Comment by radioelf** [comment]
Toroidal transformer 220-2x15V 160VA (if it is different in your station in necessary to compile code with new PID values.)
more information (in Spanish) http://radioelf.blogspot.com/2019/02/control-soldador-jbc-c245-finalizado.html
http://radioelf.blogspot.com/2019/02/calculos-termopar-c245-jbc.html
http://radioelf.blogspot.com/2019/02/obteccion-valores-pid-jbc-c-245.html
http://radioelf.blogspot.com/2019/02/control-soldador-jbc-c-245.html
and https://github.com/radioelf/C245-JBC-control/blob/master/cad/JBC_C245/Control_JBC.pdf
